#!/bin/bash

name=$(basename "$0")
red="bred"
green="bgreen"
blue="bblue"

main () {
  quine="$1"

  case "$quine" in
    "") exit_bad_usage ;;
    "-h"|"--help") exit_help ;;
    *) ;;
  esac

  run_test "$quine"

  case "$?" in
    0) exit_success ;;
    1) exit_failure ;;
    *) exit_error ;;
  esac
}

exit_bad_usage () {
  message "usage: $(usage)"
  exit_error
}

exit_help () {
  help
  exit 0
}

exit_success () {
  message "success: output matched source code"
  exit 0
}

exit_failure () {
  message "$(colorize $red red) -> missing from program output"
  message "$(colorize $green green) -> added in program output"
  message "failure: output differs from source code"
  exit 1
}

exit_error () {
  message "error"
  exit 1
}

usage () {
  echo "$name [-h] [--help] <PROGRAM>"
}

help () {
  echo "$name - a test harness for quines"
  echo -e "\nusage:"
  echo -e "\t$(usage)"
  echo -e "\nexit code:"
  echo -e "\t0 -> test succeeded, PROGRAM is a quine"
  echo -e "\t1 -> test failed, PROGRAM ist kein quine"
  echo -e "\t2 -> other error"
}

run_test () {
  # return code: 0=success 1=failure 2=error

  quine="$1"

  message "running program $quine"
  output=$("$quine")
  test "$?" != 0 && return 2
  echo "$output"

  message "comparing $quine output against its source code"
  dwdiff --color="$red","$green" "$quine" <(echo "$output")
}

colorize () {
  color="$1"
  shift
  dwdiff --color="$color" <(echo "$@") <(echo '')
}

message () {
  echo "$(colorize $blue $name): $@"
}

main "$@"
